### ISSUE TITLE
Should we use HPA

### ISSUE THREAD

**Issue by paulgmiller** [Azure/eviction-autoscaler#5]
You would still need something to gather information about failed evictions though long term that could be https://github.com/kubernetes/kubernetes/issues/128815.

However once you have that data you could model hpa resources instead of pdb watcher resources someting like this

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: <min available from pdb> 
  maxReplicas:<original metrics + maxsurge>
  metrics:
    - type: Pods
      pods:
        metric:
          name: pods_without_eviction
        target:
          type: Value
          value: 5 <original repicas count> 
```

### Positives 
*  scaling all types supported by HPA are supported 
*  can merge with other Hpas
*  No new crd needed?
### Downsides: 
* something else (deployment watcher) need to track if user that is not changes deployment and reset minReplicas
* depenendency on metric-server (who ensures HA of metric server?) 
* Need a new metric api and need to point metric server at it?

https://github.com/kubernetes-sigs/custom-metrics-apiserver

https://chatgpt.com/share/674cae4f-a758-8009-a2bf-288ef25ba215
